export const allProducts = [
  // --- Example Tobacco Product ---
  {
    "id": 2,
    "category": "tobacco",
    "name": "Watson MYO Red 50",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson Red MYO cigarette tobacco is designed with a gram weight of 50. The tobacco blend is an American Blend, delivering a strong and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. Elevate your rolling experience with Watson MYO tobacco. ",
    "imageUrl": "/products/tobacco/7c926eba441c4ab387484dbca7317b9d.png",
    "detailUrl": "/tobacco/2",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 3,
    "category": "tobacco",
    "name": "Watson MYO Red 100",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson Red MYO cigarette tobacco is designed with a gram weight of 100. The tobacco blend is an American Blend, delivering a strong and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/ab333f45fbe64611a74e6920d31ee1ee.png",
    "detailUrl": "/tobacco/3",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 4,
    "category": "tobacco",
    "name": "Watson MYO Red 200",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson Red MYO cigarette tobacco is designed with a gram weight of 200. The tobacco blend is an American Blend, delivering a strong and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/09600a6210344fc0a23c98e9c29df687.png",
    "detailUrl": "/tobacco/4",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 5,
    "category": "tobacco",
    "name": "Watson MYO Red 1000",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson Red MYO cigarette tobacco is designed with a gram weight of 1000. The tobacco blend is an American Blend, delivering a strong and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/fdeb57c5665244bc8c3012a53aee1d03.png",
    "detailUrl": "/tobacco/5",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 6,
    "category": "tobacco",
    "name": "Watson MYO Blue 50",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson Blue MYO cigarette tobacco is designed with a gram weight of 50. The tobacco blend is an American Blend, delivering a medium-strength and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/17dab4e256454a3c86de85448cc8819a.png",
    "detailUrl": "/tobacco/6",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 7,
    "category": "tobacco",
    "name": "Watson MYO Blue 100",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson MYO Blue cigarette tobacco is designed with a gram weight of 100. The tobacco blend is an American Blend, delivering a medium-strength and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/1d1637a5615e4bfba7f2c9106e4fb587.png",
    "detailUrl": "/tobacco/7",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 8,
    "category": "tobacco",
    "name": "Watson MYO Blue 200",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson MYO Blue cigarette tobacco is designed with a gram weight of 200. The tobacco blend is an American Blend, delivering a medium-strength and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/1e1c60b25f6c4fc59391cb1afe1fc0d8.png",
    "detailUrl": "/tobacco/8",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 9,
    "category": "tobacco",
    "name": "Watson MYO Blue 1000",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson MYO Blue cigarette tobacco is designed with a gram weight of 1000. The tobacco blend is an American Blend, delivering a medium-strength and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/5213d17924d348179aebfd744e63d64f.png",
    "detailUrl": "/tobacco/9",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 10,
    "category": "tobacco",
    "name": "Watson MYO Gray 50",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson MYO Gray cigarette tobacco is designed with a gram weight of 50. The tobacco blend is an American Blend, delivering a soft and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/4ae2f81979514e18af6433f4d96bed5c.png",
    "detailUrl": "/tobacco/10",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 11,
    "category": "tobacco",
    "name": "Watson MYO Gray 100",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson MYO Gray cigarette tobacco is designed with a gram weight of 100. The tobacco blend is an American Blend, delivering a soft and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/473902a91bba46a4aa65e24403f5d0f1.png",
    "detailUrl": "/tobacco/11",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 12,
    "category": "tobacco",
    "name": "Watson MYO Gray 200",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson MYO Gray cigarette tobacco is designed with a gram weight of 200. The tobacco blend is an American Blend, delivering a soft and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/5acc4d8a99bc4455aec7f6184abb97ae.png",
    "detailUrl": "/tobacco/12",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 13,
    "category": "tobacco",
    "name": "Watson MYO Gray 1000",
    "brand": "Watson",
    "tip":"MYO",
    "naturalGum": "N/A",
    "description": "Watson MYO Gray cigarette tobacco is designed with a gram weight of 1000. The tobacco blend is an American Blend, delivering a soft and flavorful smoking experience. The tobacco is packed in Doypack Packaging, providing convenience and freshness. The number of pieces per mastercase can be customized according to the customer's requirements. ",
    "imageUrl": "/products/tobacco/503292a9122e45a8a37e592415933ad7.png",
    "detailUrl": "/tobacco/13",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 14,
    "category": "tobacco",
    "name": "Watson RYO Red 25",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 25g pouch. It features a rich and flavorful American Blend. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/2bbcd0cd96ba4ee59b156f6478850b15.png",
    "detailUrl": "/tobacco/14",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 15,
    "category": "tobacco",
    "name": "Watson RYO Blue 25",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 25g pouch. It features a smooth and flavorful American Blend in a vibrant blue color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/b57f59066c4845e2a563869d0fe4c66d.png",
    "detailUrl": "/tobacco/15",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 16,
    "category": "tobacco",
    "name": "Watson RYO Gray 25",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 25g pouch. It features a smooth and flavorful American Blend in a sophisticated gray color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/5b0a26426ef243dfb77bdc2cf9b58e66.png",
    "detailUrl": "/tobacco/16",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 17,
    "category": "tobacco",
    "name": "Watson RYO Yellow 25",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 25g pouch. It features a smooth and flavorful American Blend in a vibrant yellow color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request.",
    "imageUrl": "/products/tobacco/a9527294f2f44ea2bd1f85f83104df61.png",
    "detailUrl": "/tobacco/17",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 18,
    "category": "tobacco",
    "name": "Watson RYO Beige 25",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 25g pouch. It features a smooth and flavorful American Blend in a sophisticated beige color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/1d37419170a941e4bd25da16678614d1.png",
    "detailUrl": "/tobacco/18",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 19,
    "category": "tobacco",
    "name": "Watson RYO Green 25",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 25g pouch. It features a smooth and flavorful American Blend in an attractive green color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/aff2cc68e67745f18b941c3cf33a5a76.png",
    "detailUrl": "/tobacco/19",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 20,
    "category": "tobacco",
    "name": "Watson RYO White 25",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 25g pouch. It features a smooth and flavorful American Blend in an attractive white color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request.",
    "imageUrl": "/products/tobacco/21e60afcef6b4047a2e32f9ad377b32c.png",
    "detailUrl": "/tobacco/20",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 21,
    "category": "tobacco",
    "name": "Watson RYO Black 25",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 25g pouch. It features a smooth and flavorful American Blend in an elegant black color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/d035325ca0cd46dd89c0b03b7a3c7917.png",
    "detailUrl": "/tobacco/21",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 22,
    "category": "tobacco",
    "name": "Watson RYO Dark Blue 25",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 25g pouch. It features a unique Semi Oriental blend in a dark blue color, offering a distinct and flavorful smoking experience. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/1e23e4c3cc57432791d3b44c9ab2bc97.png",
    "detailUrl": "/tobacco/22",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 23,
    "category": "tobacco",
    "name": "Watson RYO Red 50",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 50g pouch. It features a classic American Blend in a rich red color, offering a satisfying and flavorful smoking experience. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/b737bcec73ff4c1691939ceb4644ebff.png",
    "detailUrl": "/tobacco/23",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 24,
    "category": "tobacco",
    "name": "Watson RYO Blue 50",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 50g pouch. It features a smooth and flavorful American Blend in a refreshing blue color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request.",
    "imageUrl": "/products/tobacco/77452c7a001444f4a2f289859a6bb2f0.png",
    "detailUrl": "/tobacco/24",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 25,
    "category": "tobacco",
    "name": "Watson RYO Gray 50",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 50g pouch. It features a smooth and flavorful American Blend in an elegant gray color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/bcc9e27deb7546ffa191f22f634c0607.png",
    "detailUrl": "/tobacco/25",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 26,
    "category": "tobacco",
    "name": "Watson RYO Yellow 50",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 50g pouch. It features a smooth and flavorful American Blend in a vibrant yellow color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/5f6ce8f273ca449c9a9f65db3512c10b.png",
    "detailUrl": "/tobacco/26",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 27,
    "category": "tobacco",
    "name": "Watson RYO Beige 50",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 50g pouch. It features a smooth and flavorful American Blend in a sophisticated beige color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request.",
    "imageUrl": "/products/tobacco/fbf2339428c0478e9e067c7caa8f4cb9.png",
    "detailUrl": "/tobacco/27",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 28,
    "category": "tobacco",
    "name": "Watson RYO Green 50",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 50g pouch. It features a smooth and flavorful American Blend in an enticing green color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/cab15279db034e2e82f90d7eb36f4447.png",
    "detailUrl": "/tobacco/28",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 29,
    "category": "tobacco",
    "name": "Watson RYO White 50",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 50g pouch. It features a smooth and flavorful American Blend in a clean and classic white color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/87d0789a4c2244579e32000a642dfb30.png",
    "detailUrl": "/tobacco/29",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 30,
    "category": "tobacco",
    "name": "Watson RYO Black 50",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 50g pouch. It features a rich and flavorful American Blend in a sleek and bold black color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request.",
    "imageUrl": "/products/tobacco/6bba2df290cc4c778f65e4fdff9743a5.png",
    "detailUrl": "/tobacco/30",
    "specifications": [],
    "certifications": []
  },
  {
    "id": 31,
    "category": "tobacco",
    "name": "Watson RYO Dark Blue 50",
    "brand": "Watson",
    "tip":"RYO",
    "naturalGum": "N/A",
    "description": "Watson RYO tobacco is available in a 50g pouch. It features a unique and distinctive Semi Oriental blend in a deep and captivating dark blue color. The packaging is a convenient pouch with a zip closure. The number of pieces per packaging can be customized and is available upon request. ",
    "imageUrl": "/products/tobacco/3e368dc00bc240f6b41f68b2fae43a9f.png",
    "detailUrl": "/tobacco/31",
    "specifications": [],
    "certifications": []
  }
];

// You should also export the Type definition for use in your components
export const Product = {}; // You can define the type here if using TypeScript
// export const allproducts ={};